// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgcajpyjnftyheagpszn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnY2FqcHlqbmZ0eWhlYWdwc3puIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzOTY3MTUsImV4cCI6MjA4Mzk3MjcxNX0._Qsp5hNjdkp73lD9EJqBbtTGZtZD_8prcY06Taf75mI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});